<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/01_tensor_creation_and_inspection_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a single, practical reference for the most commonly used PyTorch tensor creation and inspection methods, with minimal examples and only necessary parameters.

## Prerequisites

Basic understanding of tensors (Level 1 completed).
Ability to run Python code in Google Colab.

## After This Notebook You Can

Create tensors intentionally for common scenarios.
Inspect tensor properties quickly.
Recall the right method without searching documentation.
Explain basic creation methods in interviews.

## Out of Scope

Tensor reshaping operations.
Autograd and gradients.
Model training.

---

## METHODS COVERED (SUMMARY)

Creation:

* torch.tensor
* torch.zeros
* torch.ones
* torch.empty
* torch.rand
* torch.randn
* torch.arange
* torch.linspace

Inspection:

* tensor.shape
* tensor.dtype
* tensor.device
* tensor.numel()

---

## torch.tensor

What it does:
Creates a tensor from existing data and allocates new memory.

When to use:
When you want a safe copy of Python or NumPy data.

Minimal example:

```python
import torch

x = torch.tensor([1, 2, 3], dtype=torch.float32)
x
```

Important parameters:

* dtype: numeric type of the tensor
* device: where the tensor lives (CPU by default)

Common mistake:
Assuming it shares memory with NumPy (it does not).

---

## torch.zeros

What it does:
Creates a tensor filled with zeros.

When to use:
Initialization, placeholders, masks.

Minimal example:

```python
z = torch.zeros(2, 3)
z
```

Important parameters:

* shape (positional arguments)
* dtype (optional)

Common mistake:
Forgetting the shape order.

---

## torch.ones

What it does:
Creates a tensor filled with ones.

When to use:
Bias initialization, testing, masks.

Minimal example:

```python
o = torch.ones(2, 3)
o
```

Important parameters:

* shape

Common mistake:
Assuming it behaves differently from zeros (only values differ).

---

## torch.empty

What it does:
Creates a tensor without initializing values.

When to use:
Performance-critical code where values will be overwritten.

Minimal example:

```python
e = torch.empty(2, 3)
e
```

Important parameters:

* shape

Common mistake:
Assuming values start at zero (they do not).

---

## torch.rand

What it does:
Creates a tensor with values sampled uniformly from [0, 1).

When to use:
Random initialization.

Minimal example:

```python
r = torch.rand(2, 3)
r
```

Important parameters:

* shape

Common mistake:
Confusing it with randn.

---

## torch.randn

What it does:
Creates a tensor with values sampled from a normal distribution.

When to use:
Weight initialization.

Minimal example:

```python
rn = torch.randn(2, 3)
rn
```

Important parameters:

* shape

Common mistake:
Assuming values are between 0 and 1.

---

## torch.arange

What it does:
Creates a 1D tensor with evenly spaced values.

When to use:
Indexing, ranges, positional values.

Minimal example:

```python
a = torch.arange(0, 10, 2)
a
```

Important parameters:

* start
* end (exclusive)
* step

Common mistake:
Forgetting end is exclusive.

---

## torch.linspace

What it does:
Creates a 1D tensor with a fixed number of points between two values.

When to use:
Sampling continuous ranges.

Minimal example:

```python
l = torch.linspace(0, 1, steps=5)
l
```

Important parameters:

* start
* end
* steps

Common mistake:
Confusing steps with step size.

---

## tensor.shape

What it does:
Returns the shape of the tensor.

When to use:
Debugging and validation.

Minimal example:

```python
x = torch.randn(4, 5)
x.shape
```

Common mistake:
Treating shape as mutable.

---

## tensor.dtype

What it does:
Returns the numeric type of the tensor.

When to use:
Avoiding type mismatch bugs.

Minimal example:

```python
x.dtype
```

---

## tensor.device

What it does:
Returns where the tensor is stored.

When to use:
Ensuring device consistency.

Minimal example:

```python
x.device
```

---

## tensor.numel()

What it does:
Returns the total number of elements.

When to use:
Sanity checks before reshaping.

Minimal example:

```python
x.numel()
```

---

## HANDS-ON PRACTICE

1. Create a tensor of shape (3, 4) using zeros and ones.
2. Create a random tensor and check its dtype and device.
3. Use arange and reshape it into a matrix.
4. Verify numel before and after reshaping.

---

## ONE-SENTENCE SUMMARY

Tensor creation is about choosing values, shape, dtype, and device intentionally.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_02 — Tensor Shape & Structure Methods


In [13]:
# HANDS-ON PRACTICE 1: Create a tensor of shape (3, 4) using zeros and ones.
import torch

print("Practice Task 1: Zeros tensor (3, 4)")
zeros_tensor = torch.zeros(3, 4)
print(zeros_tensor)

print("\nPractice Task 1: Ones tensor (3, 4)")
ones_tensor = torch.ones(3, 4)
print(ones_tensor)


Practice Task 1: Zeros tensor (3, 4)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Practice Task 1: Ones tensor (3, 4)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
# HANDS-ON PRACTICE 2: Create a random tensor and check its dtype and device.
import torch

print("Practice Task 2: Random tensor")
random_tensor = torch.rand(2, 2)
print(random_tensor)

print("\nPractice Task 2: dtype")
print(random_tensor.dtype)

print("\nPractice Task 2: device")
print(random_tensor.device)


Practice Task 2: Random tensor
tensor([[0.0858, 0.5229],
        [0.6666, 0.9765]])

Practice Task 2: dtype
torch.float32

Practice Task 2: device
cpu


In [15]:
# HANDS-ON PRACTICE 3: Use arange and reshape it into a matrix.
import torch

print("Practice Task 3: arange tensor")
arange_tensor = torch.arange(0, 12) # Create 12 elements for a 3x4 matrix
print(arange_tensor)

print("\nPractice Task 3: Reshaped matrix (3, 4)")
reshaped_matrix = arange_tensor.reshape(3, 4)
print(reshaped_matrix)


Practice Task 3: arange tensor
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Practice Task 3: Reshaped matrix (3, 4)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [16]:
# HANDS-ON PRACTICE 4: Verify numel before and after reshaping.
import torch

# Using the arange_tensor from the previous task
initial_tensor = torch.arange(0, 12)
print("Practice Task 4: Initial tensor numel")
print(initial_tensor.numel())

reshaped_tensor = initial_tensor.reshape(3, 4)
print("\nPractice Task 4: Reshaped tensor numel")
print(reshaped_tensor.numel())


Practice Task 4: Initial tensor numel
12

Practice Task 4: Reshaped tensor numel
12


In [17]:
# HANDS-ON PRACTICE 1: Create a tensor of shape (3, 4) using zeros and ones.
import torch

print("Practice Task 1: Zeros tensor (3, 4)")
zeros_tensor = torch.zeros(3, 4)
print(zeros_tensor)

print("\nPractice Task 1: Ones tensor (3, 4)")
ones_tensor = torch.ones(3, 4)
print(ones_tensor)


Practice Task 1: Zeros tensor (3, 4)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Practice Task 1: Ones tensor (3, 4)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [18]:
# HANDS-ON PRACTICE 2: Create a random tensor and check its dtype and device.
import torch

print("Practice Task 2: Random tensor")
random_tensor = torch.rand(2, 2)
print(random_tensor)

print("\nPractice Task 2: dtype")
print(random_tensor.dtype)

print("\nPractice Task 2: device")
print(random_tensor.device)


Practice Task 2: Random tensor
tensor([[0.5676, 0.5022],
        [0.9615, 0.4778]])

Practice Task 2: dtype
torch.float32

Practice Task 2: device
cpu


In [19]:
# HANDS-ON PRACTICE 3: Use arange and reshape it into a matrix.
import torch

print("Practice Task 3: arange tensor")
arange_tensor = torch.arange(0, 12) # Create 12 elements for a 3x4 matrix
print(arange_tensor)

print("\nPractice Task 3: Reshaped matrix (3, 4)")
reshaped_matrix = arange_tensor.reshape(3, 4)
print(reshaped_matrix)


Practice Task 3: arange tensor
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Practice Task 3: Reshaped matrix (3, 4)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [20]:
# HANDS-ON PRACTICE 4: Verify numel before and after reshaping.
import torch

# Using the arange_tensor from the previous task
initial_tensor = torch.arange(0, 12)
print("Practice Task 4: Initial tensor numel")
print(initial_tensor.numel())

reshaped_tensor = initial_tensor.reshape(3, 4)
print("\nPractice Task 4: Reshaped tensor numel")
print(reshaped_tensor.numel())


Practice Task 4: Initial tensor numel
12

Practice Task 4: Reshaped tensor numel
12


In [1]:
import torch

# torch.tensor
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print("torch.tensor example:")
print(x)


torch.tensor example:
tensor([1., 2., 3.])


In [2]:
# torch.zeros
z = torch.zeros(2, 3)
print("\ntorch.zeros example:")
print(z)



torch.zeros example:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# torch.ones
o = torch.ones(2, 3)
print("\ntorch.ones example:")
print(o)



torch.ones example:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
# torch.empty
e = torch.empty(2, 3)
print("\ntorch.empty example:")
print(e)



torch.empty example:
tensor([[9.2712e-33, 0.0000e+00, 9.2703e-33],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])


In [5]:
# torch.rand
r = torch.rand(2, 3)
print("\ntorch.rand example:")
print(r)



torch.rand example:
tensor([[0.8532, 0.9739, 0.6209],
        [0.9566, 0.4975, 0.5147]])


In [6]:
# torch.randn
rn = torch.randn(2, 3)
print("\ntorch.randn example:")
print(rn)



torch.randn example:
tensor([[-0.8798, -1.2305, -1.0401],
        [-0.4542, -0.7837,  0.1046]])


In [7]:
# torch.arange
a = torch.arange(0, 10, 2)
print("\ntorch.arange example:")
print(a)



torch.arange example:
tensor([0, 2, 4, 6, 8])


In [8]:
# torch.linspace
l = torch.linspace(0, 1, steps=5)
print("\ntorch.linspace example:")
print(l)



torch.linspace example:
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
# Inspection Methods
x_inspect = torch.randn(4, 5)

# tensor.shape
print("\ntensor.shape example:")
print(x_inspect.shape)



tensor.shape example:
torch.Size([4, 5])


In [10]:
# tensor.dtype
print("\ntensor.dtype example:")
print(x_inspect.dtype)



tensor.dtype example:
torch.float32


In [11]:
# tensor.device
print("\ntensor.device example:")
print(x_inspect.device)



tensor.device example:
cpu


In [12]:
# tensor.numel()
print("\ntensor.numel() example:")
print(x_inspect.numel())



tensor.numel() example:
20
