<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/02_tensor_shape_and_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a single, practical reference for PyTorch tensor shape and structure methods so you can change tensor layout safely and intentionally.

## Prerequisites

Level 1 completed (tensors, memory, reshaping concepts).
Ability to run Python code in Google Colab.

## After This Notebook You Can

Reshape tensors without breaking meaning.
Choose between view and reshape correctly.
Add or remove dimensions safely.
Reorder dimensions intentionally.
Recall the right method quickly during debugging or interviews.

## Out of Scope

Broadcasting rules.
Advanced indexing.
Autograd internals.

---

## METHODS COVERED (SUMMARY)

Reshaping and structure:

* tensor.reshape
* tensor.view
* tensor.flatten
* tensor.squeeze
* tensor.unsqueeze
* tensor.permute
* tensor.transpose
* tensor.contiguous

---

## tensor.reshape

What it does:
Changes the shape of a tensor while keeping the same data.

When to use:
Default choice when reshaping unless you explicitly need shared memory.

Minimal example:

```python
import torch

x = torch.arange(6)
x.reshape(2, 3)
```

Important parameters:

* new shape (tuple or positional arguments)

Common mistake:
Assuming it always returns a view (it may create a copy).

---

## tensor.view

What it does:
Returns a new view of the same tensor with a different shape.

When to use:
When you want reshaping without allocating new memory.

Minimal example:

```python
x = torch.arange(6)
x.view(2, 3)
```

Important parameters:

* new shape

Common mistake:
Using view on non-contiguous tensors (will error).

---

## tensor.flatten

What it does:
Flattens a tensor into a 1D tensor or partially flattens selected dimensions.

When to use:
Before feeding tensors into linear layers.

Minimal example:

```python
x = torch.randn(2, 3, 4)
x.flatten()
```

Important parameters:

* start_dim
* end_dim

Common mistake:
Flattening batch dimension unintentionally.

---

## tensor.squeeze

What it does:
Removes dimensions of size 1.

When to use:
Cleaning up tensors with unnecessary singleton dimensions.

Minimal example:

```python
x = torch.randn(1, 3, 1)
x.squeeze()
```

Important parameters:

* dim (optional)

Common mistake:
Accidentally removing the batch dimension.

---

## tensor.unsqueeze

What it does:
Adds a dimension of size 1 at the specified position.

When to use:
Adding batch or channel dimensions.

Minimal example:

```python
v = torch.tensor([1, 2, 3])
v.unsqueeze(0)
```

Important parameters:

* dim

Common mistake:
Adding dimension at the wrong index.

---

## tensor.permute

What it does:
Reorders the dimensions of a tensor.

When to use:
Changing data layout, such as channel-last to channel-first.

Minimal example:

```python
img = torch.randn(3, 32, 32)
img.permute(1, 2, 0)
```

Important parameters:

* dimension order (tuple)

Common mistake:
Forgetting to update downstream code expectations.

---

## tensor.transpose

What it does:
Swaps two dimensions of a tensor.

When to use:
Simple dimension swaps, especially for matrices.

Minimal example:

```python
m = torch.randn(2, 3)
m.transpose(0, 1)
```

Important parameters:

* dim0
* dim1

Common mistake:
Assuming transpose works for more than two dimensions.

---

## tensor.contiguous

What it does:
Returns a contiguous tensor in memory.

When to use:
Before calling view on a permuted or transposed tensor.

Minimal example:

```python
x = torch.randn(2, 3)
y = x.transpose(0, 1)
y.is_contiguous(), y.contiguous().is_contiguous()
```

Important parameters:
None

Common mistake:
Using contiguous without understanding why it is needed.

---

## HANDS-ON PRACTICE

1. Create a tensor of shape (2, 3, 4) and flatten only the last two dimensions.
2. Add and then remove a batch dimension safely.
3. Permute an image tensor from (C, H, W) to (H, W, C).
4. Try using view on a transposed tensor and fix it using contiguous().

---

## METHODS RECAP (ONE PLACE)

reshape, view, flatten, squeeze, unsqueeze, permute, transpose, contiguous

---

## ONE-SENTENCE SUMMARY

Shape methods change structure, not data, and must respect meaning and memory.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_03 — Tensor Math & Reduction Methods


### `tensor.reshape` example

In [1]:
import torch

x = torch.arange(6)
reshaped_x = x.reshape(2, 3)
print("Original tensor:", x)
print("Reshaped tensor:", reshaped_x)
print("Original shape:", x.shape)
print("Reshaped shape:", reshaped_x.shape)

Original tensor: tensor([0, 1, 2, 3, 4, 5])
Reshaped tensor: tensor([[0, 1, 2],
        [3, 4, 5]])
Original shape: torch.Size([6])
Reshaped shape: torch.Size([2, 3])


### `tensor.view` example

In [2]:
import torch

x = torch.arange(6)
viewed_x = x.view(2, 3)
print("Original tensor:", x)
print("Viewed tensor:", viewed_x)
print("Original shape:", x.shape)
print("Viewed shape:", viewed_x.shape)
# Check if memory is shared
x[0] = 99
print("Modified original tensor:", x)
print("View after original modified:", viewed_x)

Original tensor: tensor([0, 1, 2, 3, 4, 5])
Viewed tensor: tensor([[0, 1, 2],
        [3, 4, 5]])
Original shape: torch.Size([6])
Viewed shape: torch.Size([2, 3])
Modified original tensor: tensor([99,  1,  2,  3,  4,  5])
View after original modified: tensor([[99,  1,  2],
        [ 3,  4,  5]])


### `tensor.flatten` example

In [3]:
import torch

x = torch.randn(2, 3, 4)
flattened_x = x.flatten()
print("Original tensor shape:", x.shape)
print("Flattened tensor shape:", flattened_x.shape)

Original tensor shape: torch.Size([2, 3, 4])
Flattened tensor shape: torch.Size([24])


### `tensor.squeeze` example

In [4]:
import torch

x = torch.randn(1, 3, 1)
squeezed_x = x.squeeze()
print("Original tensor shape:", x.shape)
print("Squeezed tensor shape:", squeezed_x.shape)

y = torch.randn(1, 5, 1, 2)
squeezed_dim_y = y.squeeze(dim=2)
print("\nOriginal tensor y shape:", y.shape)
print("Squeezed dim 2 of y shape:", squeezed_dim_y.shape)

Original tensor shape: torch.Size([1, 3, 1])
Squeezed tensor shape: torch.Size([3])

Original tensor y shape: torch.Size([1, 5, 1, 2])
Squeezed dim 2 of y shape: torch.Size([1, 5, 2])


### `tensor.unsqueeze` example

In [5]:
import torch

v = torch.tensor([1, 2, 3])
unsqueezed_v = v.unsqueeze(0)
print("Original tensor shape:", v.shape)
print("Unsqueezed tensor shape (dim 0):", unsqueezed_v.shape)

unsqueezed_v_dim1 = v.unsqueeze(1)
print("Unsqueezed tensor shape (dim 1):", unsqueezed_v_dim1.shape)

Original tensor shape: torch.Size([3])
Unsqueezed tensor shape (dim 0): torch.Size([1, 3])
Unsqueezed tensor shape (dim 1): torch.Size([3, 1])


### `tensor.permute` example

In [6]:
import torch

img = torch.randn(3, 32, 32) # C, H, W
permuted_img = img.permute(1, 2, 0) # H, W, C
print("Original image shape (C, H, W):", img.shape)
print("Permuted image shape (H, W, C):", permuted_img.shape)

Original image shape (C, H, W): torch.Size([3, 32, 32])
Permuted image shape (H, W, C): torch.Size([32, 32, 3])


### `tensor.transpose` example

In [7]:
import torch

m = torch.randn(2, 3)
transposed_m = m.transpose(0, 1)
print("Original matrix shape:", m.shape)
print("Transposed matrix shape:", transposed_m.shape)
print("\nOriginal matrix:\n", m)
print("\nTransposed matrix:\n", transposed_m)

Original matrix shape: torch.Size([2, 3])
Transposed matrix shape: torch.Size([3, 2])

Original matrix:
 tensor([[-0.1433, -0.5129,  0.6119],
        [-0.3081, -1.5291, -0.5405]])

Transposed matrix:
 tensor([[-0.1433, -0.3081],
        [-0.5129, -1.5291],
        [ 0.6119, -0.5405]])


### `tensor.contiguous` example

In [8]:
import torch

x = torch.randn(2, 3)
y = x.transpose(0, 1)
print("Original tensor x is contiguous:", x.is_contiguous())
print("Transposed tensor y is contiguous:", y.is_contiguous())

y_contiguous = y.contiguous()
print("y.contiguous() is contiguous:", y_contiguous.is_contiguous())

Original tensor x is contiguous: True
Transposed tensor y is contiguous: False
y.contiguous() is contiguous: True


## Solutions to HANDS-ON PRACTICE

### 1. Create a tensor of shape (2, 3, 4) and flatten only the last two dimensions.

In [9]:
import torch

tensor_3d = torch.arange(2 * 3 * 4).reshape(2, 3, 4)
print("Original tensor:\n", tensor_3d)
print("Original shape:", tensor_3d.shape)

# Flatten only the last two dimensions (from dim 1 to dim 2)
flattened_last_two_dims = tensor_3d.flatten(start_dim=1)
print("\nTensor after flattening last two dimensions:\n", flattened_last_two_dims)
print("Shape after flattening last two dimensions:", flattened_last_two_dims.shape)

Original tensor:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Original shape: torch.Size([2, 3, 4])

Tensor after flattening last two dimensions:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
Shape after flattening last two dimensions: torch.Size([2, 12])


### 2. Add and then remove a batch dimension safely.

In [10]:
import torch

x = torch.randn(3, 5) # Example tensor
print("Original tensor shape:", x.shape)

# Add a batch dimension at the beginning (dim 0)
x_with_batch = x.unsqueeze(0)
print("Shape after adding batch dimension:", x_with_batch.shape)

# Remove the batch dimension
x_without_batch = x_with_batch.squeeze(0)
print("Shape after removing batch dimension:", x_without_batch.shape)

# Verify original shape is restored
print("Original shape restored:", x.shape == x_without_batch.shape)

Original tensor shape: torch.Size([3, 5])
Shape after adding batch dimension: torch.Size([1, 3, 5])
Shape after removing batch dimension: torch.Size([3, 5])
Original shape restored: True


### 3. Permute an image tensor from (C, H, W) to (H, W, C).

In [11]:
import torch

# Simulate an image tensor (Channels, Height, Width)
image_chw = torch.randn(3, 64, 128) # 3 channels, 64 height, 128 width
print("Original image shape (C, H, W):", image_chw.shape)

# Permute to (H, W, C)
image_hwc = image_chw.permute(1, 2, 0)
print("Permuted image shape (H, W, C):", image_hwc.shape)

# You can also permute back
image_chw_back = image_hwc.permute(2, 0, 1)
print("Permuted back to (C, H, W) shape:", image_chw_back.shape)
print("Original tensor equals permuted back tensor:", torch.equal(image_chw, image_chw_back))

Original image shape (C, H, W): torch.Size([3, 64, 128])
Permuted image shape (H, W, C): torch.Size([64, 128, 3])
Permuted back to (C, H, W) shape: torch.Size([3, 64, 128])
Original tensor equals permuted back tensor: True


### 4. Try using view on a transposed tensor and fix it using `contiguous()`.

In [12]:
import torch

x = torch.arange(6).reshape(2, 3)
print("Original tensor x:\n", x)

# Transpose the tensor
y = x.transpose(0, 1)
print("\nTransposed tensor y:\n", y)
print("y is contiguous:", y.is_contiguous())

# Trying to use view on a non-contiguous tensor will raise a RuntimeError
try:
    y.view(3, 2)
except RuntimeError as e:
    print(f"\nError when calling view on non-contiguous tensor: {e}")

# Fix it by making it contiguous first
y_contiguous = y.contiguous()
print("\ny_contiguous is contiguous:", y_contiguous.is_contiguous())

# Now view works
viewed_y_fixed = y_contiguous.view(3, 2)
print("\nViewed tensor after making it contiguous:\n", viewed_y_fixed)
print("Shape of viewed_y_fixed:", viewed_y_fixed.shape)

Original tensor x:
 tensor([[0, 1, 2],
        [3, 4, 5]])

Transposed tensor y:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
y is contiguous: False

y_contiguous is contiguous: True

Viewed tensor after making it contiguous:
 tensor([[0, 3],
        [1, 4],
        [2, 5]])
Shape of viewed_y_fixed: torch.Size([3, 2])
