<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/04_tensor_indexing_and_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a clear, example-driven reference for selecting, slicing, and filtering data from PyTorch tensors.

## Prerequisites

Level 1 completed.
Basic understanding of tensor shapes and dimensions.

## After This Notebook You Can

Index and slice tensors confidently.
Use boolean masks for selection.
Select elements conditionally.
Explain indexing methods in interviews.

## Out of Scope

Advanced autograd behavior.
Sparse tensors.
Performance optimization.

---

## METHODS COVERED (SUMMARY)

Indexing and selection:

* Basic indexing
* Slicing
* Boolean masking
* torch.where
* torch.gather
* torch.nonzero

---

## Basic Indexing

What it does:
Selects elements using integer indices.

When to use:
Accessing specific elements or rows.

Minimal example:

```python
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60]])
x[0]
x[1, 2]
```

Common mistake:
Forgetting that indexing reduces dimensions.

---

## Slicing

What it does:
Selects ranges of elements along dimensions.

When to use:
Extracting sub-tensors.

Minimal example:

```python
x[:, :2]
```

Common mistake:
Assuming slicing copies data (it often shares memory).

---

## Boolean Masking

What it does:
Selects elements where a condition is true.

When to use:
Filtering data based on conditions.

Minimal example:

```python
x = torch.tensor([1, 5, 3, 8])
mask = x > 3
x[mask]
```

Common mistake:
Mask shape not matching tensor shape.

---

## torch.where

What it does:
Selects elements based on a condition.

When to use:
Conditional replacement or selection.

Minimal example:

```python
x = torch.tensor([1, 5, 3, 8])
torch.where(x > 3, x, torch.tensor(0))
```

Important parameters:

* condition
* x
* y

Common mistake:
Forgetting x and y must be broadcastable.

---

## torch.gather

What it does:
Gathers values along an axis using indices.

When to use:
Selecting elements using index tensors.

Minimal example:

```python
x = torch.tensor([[10, 20, 30], [40, 50, 60]])
idx = torch.tensor([[2, 1], [0, 2]])
torch.gather(x, 1, idx)
```

Important parameters:

* input
* dim
* index

Common mistake:
Misunderstanding index shape requirements.

---

## torch.nonzero

What it does:
Returns indices of non-zero elements.

When to use:
Finding positions of valid entries.

Minimal example:

```python
x = torch.tensor([0, 1, 0, 3])
torch.nonzero(x)
```

Common mistake:
Assuming it returns values instead of indices.

---

## HANDS-ON PRACTICE

1. Slice a 2D tensor to extract specific columns.
2. Use boolean masking to filter values greater than a threshold.
3. Use torch.where to replace negative values with zero.
4. Use gather to select elements using an index tensor.

---

## METHODS RECAP (ONE PLACE)

Basic indexing, slicing, boolean masking, where, gather, nonzero

---

## ONE-SENTENCE SUMMARY

Indexing methods select data, they do not change tensor values.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_05 — Tensor Memory & Copy Methods


In [1]:
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60]])
print("Original tensor x:", x)

# Basic indexing: Access a row
print("x[0]:", x[0])

# Basic indexing: Access a specific element
print("x[1, 2]:", x[1, 2])

Original tensor x: tensor([[10, 20, 30],
        [40, 50, 60]])
x[0]: tensor([10, 20, 30])
x[1, 2]: tensor(60)


In [2]:
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original tensor x:", x)

# Slicing: Select all rows and first two columns
print("x[:, :2]:", x[:, :2])

# Slicing: Select specific rows and columns
print("x[0:2, 1:]:", x[0:2, 1:])

Original tensor x: tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
x[:, :2]: tensor([[10, 20],
        [40, 50],
        [70, 80]])
x[0:2, 1:]: tensor([[20, 30],
        [50, 60]])


In [3]:
import torch

x = torch.tensor([1, 5, 3, 8, 2, 9, 4])
print("Original tensor x:", x)

# Create a boolean mask
mask = x > 3
print("Mask (x > 3):", mask)

# Apply the boolean mask
print("x[mask]:", x[mask])

Original tensor x: tensor([1, 5, 3, 8, 2, 9, 4])
Mask (x > 3): tensor([False,  True, False,  True, False,  True,  True])
x[mask]: tensor([5, 8, 9, 4])


In [4]:
import torch

x = torch.tensor([1, 5, -3, 8, -2, 9, 0])
print("Original tensor x:", x)

# Use torch.where to replace negative values with 0
result = torch.where(x < 0, torch.tensor(0), x)
print("torch.where(x < 0, 0, x):", result)

# Use torch.where for conditional selection
y = torch.tensor([10, 20, 30, 40, 50, 60, 70])
condition = x > 3
selected = torch.where(condition, x, y)
print("torch.where(x > 3, x, y):", selected)

Original tensor x: tensor([ 1,  5, -3,  8, -2,  9,  0])
torch.where(x < 0, 0, x): tensor([1, 5, 0, 8, 0, 9, 0])
torch.where(x > 3, x, y): tensor([10,  5, 30,  8, 50,  9, 70])


In [5]:
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original tensor x:\n", x)

# Indices to gather along dimension 1 (columns)
idx = torch.tensor([[2, 1], [0, 2], [1, 0]]) # For each row, pick elements at these column indices
print("Indices to gather:\n", idx)

result = torch.gather(x, 1, idx)
print("torch.gather(x, 1, idx):\n", result)

# Example for dim 0 (rows)
x_dim0 = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
idx_dim0 = torch.tensor([[0,0,0],[1,1,1]]) # Gather row 0 for first result row, row 1 for second
print("\nOriginal tensor x_dim0:\n", x_dim0)
print("Indices to gather along dim 0:\n", idx_dim0)
result_dim0 = torch.gather(x_dim0, 0, idx_dim0)
print("torch.gather(x_dim0, 0, idx_dim0):\n", result_dim0)

Original tensor x:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
Indices to gather:
 tensor([[2, 1],
        [0, 2],
        [1, 0]])
torch.gather(x, 1, idx):
 tensor([[30, 20],
        [40, 60],
        [80, 70]])

Original tensor x_dim0:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Indices to gather along dim 0:
 tensor([[0, 0, 0],
        [1, 1, 1]])
torch.gather(x_dim0, 0, idx_dim0):
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
import torch

x = torch.tensor([0, 1, 0, 3, 0, 5, 0])
print("Original 1D tensor x:", x)

# Find indices of non-zero elements in a 1D tensor
non_zero_indices_1d = torch.nonzero(x)
print("torch.nonzero(x) (1D):\n", non_zero_indices_1d)

y = torch.tensor([[0, 1, 0], [2, 0, 3], [0, 0, 4]])
print("\nOriginal 2D tensor y:\n", y)

# Find indices of non-zero elements in a 2D tensor
non_zero_indices_2d = torch.nonzero(y)
print("torch.nonzero(y) (2D):\n", non_zero_indices_2d)

# As tuple (useful for direct indexing)
print("torch.nonzero(y, as_tuple=True):\n", torch.nonzero(y, as_tuple=True))

Original 1D tensor x: tensor([0, 1, 0, 3, 0, 5, 0])
torch.nonzero(x) (1D):
 tensor([[1],
        [3],
        [5]])

Original 2D tensor y:
 tensor([[0, 1, 0],
        [2, 0, 3],
        [0, 0, 4]])
torch.nonzero(y) (2D):
 tensor([[0, 1],
        [1, 0],
        [1, 2],
        [2, 2]])
torch.nonzero(y, as_tuple=True):
 (tensor([0, 1, 1, 2]), tensor([1, 0, 2, 2]))
