<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/04_tensor_indexing_and_selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a clear, example-driven reference for selecting, slicing, and filtering data from PyTorch tensors.

## Prerequisites

Level 1 completed.
Basic understanding of tensor shapes and dimensions.

## After This Notebook You Can

Index and slice tensors confidently.
Use boolean masks for selection.
Select elements conditionally.
Explain indexing methods in interviews.

## Out of Scope

Advanced autograd behavior.
Sparse tensors.
Performance optimization.

---

## METHODS COVERED (SUMMARY)

Indexing and selection:

* Basic indexing
* Slicing
* Boolean masking
* torch.where
* torch.gather
* torch.nonzero

---

## Basic Indexing

What it does:
Selects elements using integer indices.

When to use:
Accessing specific elements or rows.

Minimal example:

```python
import torch

x = torch.tensor([[10, 20, 30], [40, 50, 60]])
x[0]
x[1, 2]
```

Common mistake:
Forgetting that indexing reduces dimensions.

---

## Slicing

What it does:
Selects ranges of elements along dimensions.

When to use:
Extracting sub-tensors.

Minimal example:

```python
x[:, :2]
```

Common mistake:
Assuming slicing copies data (it often shares memory).

---

## Boolean Masking

What it does:
Selects elements where a condition is true.

When to use:
Filtering data based on conditions.

Minimal example:

```python
x = torch.tensor([1, 5, 3, 8])
mask = x > 3
x[mask]
```

Common mistake:
Mask shape not matching tensor shape.

---

## torch.where

What it does:
Selects elements based on a condition.

When to use:
Conditional replacement or selection.

Minimal example:

```python
x = torch.tensor([1, 5, 3, 8])
torch.where(x > 3, x, torch.tensor(0))
```

Important parameters:

* condition
* x
* y

Common mistake:
Forgetting x and y must be broadcastable.

---

## torch.gather

What it does:
Gathers values along an axis using indices.

When to use:
Selecting elements using index tensors.

Minimal example:

```python
x = torch.tensor([[10, 20, 30], [40, 50, 60]])
idx = torch.tensor([[2, 1], [0, 2]])
torch.gather(x, 1, idx)
```

Important parameters:

* input
* dim
* index

Common mistake:
Misunderstanding index shape requirements.

---

## torch.nonzero

What it does:
Returns indices of non-zero elements.

When to use:
Finding positions of valid entries.

Minimal example:

```python
x = torch.tensor([0, 1, 0, 3])
torch.nonzero(x)
```

Common mistake:
Assuming it returns values instead of indices.

---

## HANDS-ON PRACTICE

1. Slice a 2D tensor to extract specific columns.
2. Use boolean masking to filter values greater than a threshold.
3. Use torch.where to replace negative values with zero.
4. Use gather to select elements using an index tensor.

---

## METHODS RECAP (ONE PLACE)

Basic indexing, slicing, boolean masking, where, gather, nonzero

---

## ONE-SENTENCE SUMMARY

Indexing methods select data, they do not change tensor values.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_05 — Tensor Memory & Copy Methods


In [1]:
import torch

print("---> Basic Indexing <---")
x = torch.tensor([[10, 20, 30], [40, 50, 60]])
print("Original tensor x:\n", x)
print("x[0]:", x[0])
print("x[1, 2]:", x[1, 2])

print("\n---> Slicing <---")
print("Original tensor x:\n", x)
print("x[:, :2]:\n", x[:, :2])

print("\n---> Boolean Masking <---")
x_mask = torch.tensor([1, 5, 3, 8])
print("Original tensor x_mask:\n", x_mask)
mask = x_mask > 3
print("Mask (x_mask > 3):", mask)
print("x_mask[mask]:", x_mask[mask])

print("\n---> torch.where <---")
x_where = torch.tensor([1, 5, 3, 8])
print("Original tensor x_where:\n", x_where)
print("torch.where(x_where > 3, x_where, torch.tensor(0)):\n", torch.where(x_where > 3, x_where, torch.tensor(0)))

print("\n---> torch.gather <---")
x_gather = torch.tensor([[10, 20, 30], [40, 50, 60]])
idx_gather = torch.tensor([[2, 1], [0, 2]])
print("Original tensor x_gather:\n", x_gather)
print("Index tensor idx_gather:\n", idx_gather)
print("torch.gather(x_gather, 1, idx_gather):\n", torch.gather(x_gather, 1, idx_gather))

print("\n---> torch.nonzero <---")
x_nonzero = torch.tensor([0, 1, 0, 3])
print("Original tensor x_nonzero:\n", x_nonzero)
print("torch.nonzero(x_nonzero):\n", torch.nonzero(x_nonzero))

---> Basic Indexing <---
Original tensor x:
 tensor([[10, 20, 30],
        [40, 50, 60]])
x[0]: tensor([10, 20, 30])
x[1, 2]: tensor(60)

---> Slicing <---
Original tensor x:
 tensor([[10, 20, 30],
        [40, 50, 60]])
x[:, :2]:
 tensor([[10, 20],
        [40, 50]])

---> Boolean Masking <---
Original tensor x_mask:
 tensor([1, 5, 3, 8])
Mask (x_mask > 3): tensor([False,  True, False,  True])
x_mask[mask]: tensor([5, 8])

---> torch.where <---
Original tensor x_where:
 tensor([1, 5, 3, 8])
torch.where(x_where > 3, x_where, torch.tensor(0)):
 tensor([0, 5, 0, 8])

---> torch.gather <---
Original tensor x_gather:
 tensor([[10, 20, 30],
        [40, 50, 60]])
Index tensor idx_gather:
 tensor([[2, 1],
        [0, 2]])
torch.gather(x_gather, 1, idx_gather):
 tensor([[30, 20],
        [40, 60]])

---> torch.nonzero <---
Original tensor x_nonzero:
 tensor([0, 1, 0, 3])
torch.nonzero(x_nonzero):
 tensor([[1],
        [3]])
