<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/07_random_and_initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a clear, example-driven reference for PyTorch randomness and initialization methods so experiments are reproducible and initializations are intentional.

## Prerequisites

Level 1 completed.
Basic understanding of tensors and math.

## After This Notebook You Can

Control randomness for reproducible results.
Choose appropriate random initialization methods.
Explain randomness-related APIs in interviews.
Diagnose bugs caused by uncontrolled randomness.

## Out of Scope

Advanced initialization strategies.
Distributed randomness control.
Randomness in CUDA kernels.

---

## METHODS COVERED (SUMMARY)

Randomness control:

* torch.manual_seed

Random tensor generation:

* torch.rand
* torch.randn
* torch.randint
* torch.normal
* torch.uniform

---

## torch.manual_seed

What it does:
Sets the seed for generating random numbers.

When to use:
Ensuring reproducible experiments.

Minimal example:

```python
import torch

torch.manual_seed(42)
x1 = torch.rand(3)

torch.manual_seed(42)
x2 = torch.rand(3)

x1, x2
```

Important parameters:

* seed (integer)

Common mistake:
Assuming it affects NumPy randomness (it does not).

---

## torch.rand

What it does:
Generates random values from a uniform distribution in [0, 1).

When to use:
Generic random initialization.

Minimal example:

```python
torch.rand(2, 3)
```

Common mistake:
Assuming values are normally distributed.

---

## torch.randn

What it does:
Generates random values from a standard normal distribution.

When to use:
Weight initialization.

Minimal example:

```python
torch.randn(2, 3)
```

Common mistake:
Assuming values lie between 0 and 1.

---

## torch.randint

What it does:
Generates random integers within a specified range.

When to use:
Random class labels or indices.

Minimal example:

```python
torch.randint(0, 10, (5,))
```

Important parameters:

* low
* high
* size

Common mistake:
Forgetting high is exclusive.

---

## torch.normal

What it does:
Generates random values from a normal distribution with specified mean and std.

When to use:
Custom normal initialization.

Minimal example:

```python
torch.normal(mean=0.0, std=1.0, size=(2, 3))
```

Important parameters:

* mean
* std
* size

Common mistake:
Mixing scalar and tensor means unintentionally.

---

## torch.uniform

What it does:
Generates random values from a uniform distribution in a specified range.

When to use:
Controlled uniform sampling.

Minimal example:

```python
torch.empty(2, 3).uniform_(0, 1)
```

Important parameters:

* low
* high

Common mistake:
Forgetting this is an in-place operation.

---

## HANDS-ON PRACTICE

1. Set a manual seed and generate two identical random tensors.
2. Compare outputs of rand and randn.
3. Generate random integers and verify range limits.
4. Initialize a tensor using uniform_ and inspect its values.

---

## METHODS RECAP (ONE PLACE)

manual_seed, rand, randn, randint, normal, uniform

---

## ONE-SENTENCE SUMMARY

Randomness must be controlled explicitly to make experiments repeatable.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_08 — nn.Module & Parameter Utilities (intro level)


In [1]:
import torch

# torch.manual_seed
# Sets the seed for generating random numbers to ensure reproducibility.
torch.manual_seed(42)
x1 = torch.rand(3)

torch.manual_seed(42) # Set the seed again for x2 to be identical to x1
x2 = torch.rand(3)

print(f"x1 after manual_seed(42): {x1}")
print(f"x2 after manual_seed(42): {x2}")
print(f"Are x1 and x2 identical? {torch.equal(x1, x2)}")

x1 after manual_seed(42): tensor([0.8823, 0.9150, 0.3829])
x2 after manual_seed(42): tensor([0.8823, 0.9150, 0.3829])
Are x1 and x2 identical? True


In [2]:
import torch

# torch.rand
# Generates random values from a uniform distribution in [0, 1).
rand_tensor = torch.rand(2, 3)
print(f"Tensor from torch.rand:\n{rand_tensor}")

Tensor from torch.rand:
tensor([[0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [3]:
import torch

# torch.randn
# Generates random values from a standard normal distribution (mean=0, std=1).
randn_tensor = torch.randn(2, 3)
print(f"Tensor from torch.randn:\n{randn_tensor}")

Tensor from torch.randn:
tensor([[ 1.5231,  0.6647, -1.0324],
        [-0.2770, -0.1671, -0.1079]])


In [4]:
import torch

# torch.randint
# Generates random integers within a specified range [low, high).
randint_tensor = torch.randint(0, 10, (5,))
print(f"Tensor from torch.randint (0 to 9):\n{randint_tensor}")

Tensor from torch.randint (0 to 9):
tensor([6, 3, 1, 9, 3])


In [5]:
import torch

# torch.normal
# Generates random values from a normal distribution with specified mean and std.
normal_tensor = torch.normal(mean=0.0, std=1.0, size=(2, 3))
print(f"Tensor from torch.normal (mean=0, std=1):\n{normal_tensor}")

# Example with different mean and std
custom_normal_tensor = torch.normal(mean=torch.tensor([0.0, 1.0]), std=torch.tensor([1.0, 0.5]))
print(f"Tensor from torch.normal (custom mean/std):\n{custom_normal_tensor}")

Tensor from torch.normal (mean=0, std=1):
tensor([[ 0.6688, -0.7077, -0.3267],
        [-0.2788, -0.4220, -1.3323]])
Tensor from torch.normal (custom mean/std):
tensor([-0.3639,  1.0757])


In [6]:
import torch

# torch.uniform (in-place operation on an existing tensor)
# Generates random values from a uniform distribution in a specified range [low, high).
uniform_tensor = torch.empty(2, 3).uniform_(0, 5) # Values between 0 (inclusive) and 5 (exclusive)
print(f"Tensor from torch.uniform (0 to 5):\n{uniform_tensor}")

Tensor from torch.uniform (0 to 5):
tensor([[3.5521, 4.7321, 3.9451],
        [1.4071, 3.9432, 2.9473]])
