<a href="https://colab.research.google.com/github/sufiyansayyed19/myTorch/blob/main/03_tensor_math_and_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook Goal

Provide a compact, example-driven reference for common PyTorch tensor math and reduction methods used in everyday model code and interviews.

## Prerequisites

Level 1 completed (tensors, shapes, memory).
Basic familiarity with Python arithmetic.

## After This Notebook You Can

Apply elementwise math operations correctly.
Use reduction operations intentionally.
Predict output shapes of reductions.
Explain common math methods in interviews.

## Out of Scope

Broadcasting rules in depth.
Autograd mechanics.
Loss functions.

---

## METHODS COVERED (SUMMARY)

Elementwise math:

* add / sub / mul / div
* abs
* pow
* sqrt

Reductions:

* sum
* mean
* max
* min
* argmax
* argmin

---

## Elementwise Operations (add / sub / mul / div)

What they do:
Apply arithmetic operation elementwise between tensors or tensor and scalar.

When to use:
Feature scaling, updates, simple transformations.

Minimal examples:

```python
import torch

x = torch.tensor([1.0, 2.0, 3.0])

x + 1
x * 2
x - 0.5
x / 2
```

Important parameters:
None (operator overloads are most common).

Common mistake:
Forgetting shapes must be compatible.

---

## torch.abs

What it does:
Computes absolute value elementwise.

When to use:
Error magnitudes, distance calculations.

Minimal example:

```python
x = torch.tensor([-3.0, 2.0, -1.0])
x.abs()
```

Common mistake:
Assuming it modifies tensor in-place (it does not).

---

## torch.pow

What it does:
Raises tensor elements to a power.

When to use:
Squared errors, power transformations.

Minimal example:

```python
x = torch.tensor([1.0, 2.0, 3.0])
torch.pow(x, 2)
```

Important parameters:

* exponent

Common mistake:
Confusing with Python ** operator (both work).

---

## torch.sqrt

What it does:
Computes square root elementwise.

When to use:
Distance metrics, normalization.

Minimal example:

```python
x = torch.tensor([1.0, 4.0, 9.0])
torch.sqrt(x)
```

Common mistake:
Applying to negative values.

---

## torch.sum

What it does:
Sums tensor elements along a dimension.

When to use:
Aggregation, loss components.

Minimal example:

```python
x = torch.tensor([[1, 2], [3, 4]])
x.sum()
x.sum(dim=0)
```

Important parameters:

* dim
* keepdim

Common mistake:
Dropping dimensions unintentionally.

---

## torch.mean

What it does:
Computes mean of tensor elements.

When to use:
Averaging losses or features.

Minimal example:

```python
x.mean()
x.mean(dim=1)
```

Common mistake:
Assuming integer tensors return float means (dtype matters).

---

## torch.max / torch.min

What they do:
Return maximum or minimum values (and optionally indices).

When to use:
Thresholding, comparisons.

Minimal example:

```python
x = torch.tensor([[1, 5], [3, 2]])

x.max()
values, indices = x.max(dim=1)
values, indices
```

Important parameters:

* dim
* keepdim

Common mistake:
Ignoring returned indices when they are needed.

---

## torch.argmax / torch.argmin

What they do:
Return indices of max or min values.

When to use:
Predicted class selection.

Minimal example:

```python
scores = torch.tensor([0.1, 0.7, 0.2])
scores.argmax()
```

Important parameters:

* dim

Common mistake:
Using argmax where max value is required.

---

## HANDS-ON PRACTICE

1. Create a tensor and compute sum and mean along different dimensions.
2. Use argmax on a batch of prediction scores.
3. Square a tensor and then take its square root.
4. Compare max vs argmax outputs.

---

## METHODS RECAP (ONE PLACE)

add, sub, mul, div, abs, pow, sqrt, sum, mean, max, min, argmax, argmin

---

## ONE-SENTENCE SUMMARY

Math methods transform values, reduction methods collapse dimensions.

---

## WHERE THIS FITS NEXT

Next reference notebook:
PyTorch_Methods_04 — Tensor Indexing & Selection Methods


### Elementwise Operations: `add`, `sub`, `mul`, `div`

These operations apply arithmetic elementwise between tensors or a tensor and a scalar.

In [1]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(f"Original tensor x: {x}")
print(f"Addition (x + y): {x + y}")
print(f"Subtraction (x - 1): {x - 1}")
print(f"Multiplication (x * 2): {x * 2}")
print(f"Division (x / y): {x / y}")

Original tensor x: tensor([1., 2., 3.])
Addition (x + y): tensor([5., 7., 9.])
Subtraction (x - 1): tensor([0., 1., 2.])
Multiplication (x * 2): tensor([2., 4., 6.])
Division (x / y): tensor([0.2500, 0.4000, 0.5000])


### Elementwise Operation: `abs`

Computes the absolute value of each element in the tensor.

In [2]:
import torch

x = torch.tensor([-3.0, 2.0, -1.0])
print(f"Original tensor x: {x}")
print(f"Absolute values (x.abs()): {x.abs()}")

Original tensor x: tensor([-3.,  2., -1.])
Absolute values (x.abs()): tensor([3., 2., 1.])


### Elementwise Operation: `pow`

Raises each element in the tensor to a specified power.

In [3]:
import torch

x = torch.tensor([1.0, 2.0, 3.0])
print(f"Original tensor x: {x}")
print(f"Power (torch.pow(x, 2)): {torch.pow(x, 2)}")

Original tensor x: tensor([1., 2., 3.])
Power (torch.pow(x, 2)): tensor([1., 4., 9.])


### Elementwise Operation: `sqrt`

Computes the square root of each element in the tensor.

In [4]:
import torch

x = torch.tensor([1.0, 4.0, 9.0])
print(f"Original tensor x: {x}")
print(f"Square root (torch.sqrt(x)): {torch.sqrt(x)}")

Original tensor x: tensor([1., 4., 9.])
Square root (torch.sqrt(x)): tensor([1., 2., 3.])


### Reduction: `sum`

Sums all elements in the tensor, or along a specified dimension.

In [5]:
import torch

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f"Original tensor x:\n{x}")
print(f"Sum of all elements (x.sum()): {x.sum()}")
print(f"Sum along dim=0 (x.sum(dim=0)): {x.sum(dim=0)}")
print(f"Sum along dim=1 (x.sum(dim=1)): {x.sum(dim=1)}")

Original tensor x:
tensor([[1., 2.],
        [3., 4.]])
Sum of all elements (x.sum()): 10.0
Sum along dim=0 (x.sum(dim=0)): tensor([4., 6.])
Sum along dim=1 (x.sum(dim=1)): tensor([3., 7.])


### Reduction: `mean`

Computes the mean of all elements in the tensor, or along a specified dimension.

In [6]:
import torch

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(f"Original tensor x:\n{x}")
print(f"Mean of all elements (x.mean()): {x.mean()}")
print(f"Mean along dim=0 (x.mean(dim=0)): {x.mean(dim=0)}")
print(f"Mean along dim=1 (x.mean(dim=1)): {x.mean(dim=1)}")

Original tensor x:
tensor([[1., 2.],
        [3., 4.]])
Mean of all elements (x.mean()): 2.5
Mean along dim=0 (x.mean(dim=0)): tensor([2., 3.])
Mean along dim=1 (x.mean(dim=1)): tensor([1.5000, 3.5000])


### Reductions: `max` / `min`

Return the maximum or minimum values in the tensor, or along a specified dimension. They can also return the indices.

In [7]:
import torch

x = torch.tensor([[1, 5], [3, 2]], dtype=torch.float32)
print(f"Original tensor x:\n{x}")

print(f"Max of all elements (x.max()): {x.max()}")
print(f"Min of all elements (x.min()): {x.min()}")

values_max, indices_max = x.max(dim=1)
print(f"Max along dim=1 (values, indices): {values_max}, {indices_max}")

values_min, indices_min = x.min(dim=0)
print(f"Min along dim=0 (values, indices): {values_min}, {indices_min}")

Original tensor x:
tensor([[1., 5.],
        [3., 2.]])
Max of all elements (x.max()): 5.0
Min of all elements (x.min()): 1.0
Max along dim=1 (values, indices): tensor([5., 3.]), tensor([1, 0])
Min along dim=0 (values, indices): tensor([1., 2.]), tensor([0, 1])


### Reductions: `argmax` / `argmin`

Return the indices of the maximum or minimum values along a specified dimension.

In [8]:
import torch

scores = torch.tensor([0.1, 0.7, 0.2, 0.9])
print(f"Original scores: {scores}")
print(f"Index of max score (scores.argmax()): {scores.argmax()}")
print(f"Index of min score (scores.argmin()): {scores.argmin()}")

matrix = torch.tensor([[10, 20, 5], [30, 4, 15]], dtype=torch.float32)
print(f"\nOriginal matrix:\n{matrix}")
print(f"Argmax along dim=0 (matrix.argmax(dim=0)): {matrix.argmax(dim=0)}")
print(f"Argmin along dim=1 (matrix.argmin(dim=1)): {matrix.argmin(dim=1)}")

Original scores: tensor([0.1000, 0.7000, 0.2000, 0.9000])
Index of max score (scores.argmax()): 3
Index of min score (scores.argmin()): 0

Original matrix:
tensor([[10., 20.,  5.],
        [30.,  4., 15.]])
Argmax along dim=0 (matrix.argmax(dim=0)): tensor([1, 0, 1])
Argmin along dim=1 (matrix.argmin(dim=1)): tensor([2, 1])
